FROM eclipse-temurin:17-jdk-alpine
WORKDIR /app
COPY target/Human_Resource_Website-0.0.1-SNAPSHOT.jar Human_Resource_Website-0.0.1-SNAPSHOT.jar
EXPOSE 8080
CMD ["java", "-jar", "Human_Resource_Website-0.0.1-SNAPSHOT.jar"]
